name: Deploy Auth Frontend
on:
  push:
    branches: [ dev ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout auth-frontend
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          path: '.'

      - name: Checkout Terraform
        uses: actions/checkout@v3
        with:
          repository: 'space-metaverse/terraform'
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: 'terraform'
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2

      - name: Test setup
        run: ls -la && cd terraform && ls -la

      - name: Terraform Init
        run: |
          chmod +x ./terraform/build_image.sh
          chmod +x ./terraform/deploy_infra.sh
          ./terraform/build_image.sh
          ./terraform/deploy_infra.sh
        env:
          CI_COMMIT_REF_NAME: ${{ github.ref_name }}
          APP_NAME: ${{ secrets.APP_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}', github.ref_name)] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', github.ref_name)] }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          PATH_PATTERN: ${{ secrets.PATH_PATTERN }}
          CONTAINER_PORT: ${{ secrets.CONTAINER_PORT }}
          VPC_ID: ${{ secrets[format('VPC_ID_{0}', github.ref_name)] }}
          SUBNET_IDS: ${{ secrets[format('SUBNET_IDS_{0}', github.ref_name)] }}
          LISTNER_ARN: ${{ secrets[format('LISTNER_ARN_{0}', github.ref_name)] }}
          CLUSTER_NAME: ${{ secrets[format('CLUSTER_NAME_{0}', github.ref_name)] }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          ENV_FILE: ${{ secrets[format('ENV_{0}', github.ref_name)] }}
          DO_DESTROY: ${{ secrets.DO_DESTROY }}
